export const FETCH_TEST_TO_BE_COMPLETED = 'FETCH_TEST_TO_BE_COMPLETED';
export const SET_QUESTION_ANSWER = 'SET_QUESTION_ANSWER';
export const SAVE_TEST_ANSWERS = 'SAVE_TEST_ANSWERS';
export const SET_QUESTION_RATE = 'SET_QUESTION_RATE';
export const SET_TEST_RATING = 'SET_TEST_RATING';
export const GET_TEST_RESULT = 'GET_TEST_RESULT';
export const GET_USER_TEST_ANSWERS = 'GET_USER_TEST_ANSWERS';
